name: CICD

on:
  push:
    branches:
      -master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p  ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t anderson383/shoppingfy-front .
      - name: Publish image to docker hub
        run: docker push anderson383/shoppingfy-front:latest
  
  deploy:
    needs: build
    runs-on: aws-ec2

    steps:
      - name: Pull image from docker hub
        run: docker pull anderson383/shoppingfy-front:latest
      - name: Delete Old Container
        run: docker rm -f reactContainer
      - name: Run docker container
        run: docker run -d -p 3000:80 --name reactContainer anderson383/shoppingfy-front